# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Oh My Prvd
site_url: https://team-fireworks.github.io/ohmyprvd
repo_url: https://github.com/team-fireworks/ohmyprvd

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: ompdoc-dark
      toggle:
        icon: octicons/sun-24
        title: Switch to light theme
    - media: "(prefers-color-scheme: light)"
      scheme: ompdoc-light
      toggle:
        icon: octicons/moon-24
        title: Switch to dark theme
  font:
    text: Inter
    code: JetBrains Mono
  logo: assets/logo.svg
  favicon: assets/logo.svg
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/flame-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.suggest

nav:
  - Home: index.md
  - Tutorials:
    - tutorials/index.md
    - Installation: tutorials/installation.md
    - Fundamentals:
      - Providers: tutorials/fundamentals/providers.md
      - Startup: tutorials/fundamentals/startup.md
      - Lifecycle Methods: tutorials/fundamentals/lifecycle-methods.md
    - Net:
      - Net: tutorials/net/index.md
      - Events: tutorials/net/events.md
      - Functions: tutorials/net/functions.md
      - Middlewares: tutorials/net/middlewares.md
      - Namespaces: tutorials/net/namespaces.md
    - Components:
      - Components: tutorials/components/index.md
      - Usage: tutorials/components/usage.md
      - Attributes: tutorials/components/attributes.md
      - Inheritance: tutorials/components/inheritance.md
    - Advanced:
      - Modding: tutorials/advanced/modding.md
      - Execution Order: tutorials/advanced/execution-order.md
      - VSCode Snippets: tutorials/advanced/snippets.md
      - Philosophies: tutorials/advanced/philosophies.md
  - Examples:
    - examples/index.md
    - Projects:
      - Oh My Prvd Obby: examples/projects/omp-obby.md
  - Reference:
    - reference/index.md
    - Error Messages: reference/error-messages.md
    - Core:
      - reference/core/index.md
      - Providers:
        - reference/core/providers/index.md
        - awaitStart: reference/core/providers/await-start.md
        - onStart: reference/core/providers/on-start.md
        - preload: reference/core/providers/preload.md
        - Provider: reference/core/providers/provider.md
        - start: reference/core/providers/start.md
        - StartupStatus: reference/core/providers/startup-status.md
        - use: reference/core/providers/use.md
      - Modding:
        - reference/core/modding/index.md
        - getStartupOptions: reference/core/modding/get-startup-options.md
        - getStartupStatus: reference/core/modding/get-startup-status.md
        - onMethodImplemented: reference/core/modding/on-method-implemented.md
        - onProviderConstructed: reference/core/modding/on-provider-constructed.md
        - onProviderUsed: reference/core/modding/on-provider-used.md
      - Reflection:
        - reference/core/reflection/index.md
        - defineMetadata: reference/core/reflection/define-metadata.md
        - getMetadata: reference/core/reflection/get-metadata.md
        - deleteMetadata: reference/core/reflection/delete-metadata.md
      - Types:
        - reference/core/types/index.md
        - Options: reference/core/types/options.md
        - Provider: reference/core/types/provider.md
    - Lifecycles:
      - reference/lifecycles/index.md
      - Runtime:
        - reference/lifecycles/runtime/index.md
        - onPostSimulation: reference/lifecycles/runtime/on-post-simulation.md
        - onPreSimulation: reference/lifecycles/runtime/on-pre-simulation.md
        - onPreRender: reference/lifecycles/runtime/on-pre-render.md
        - onShutdown: reference/lifecycles/runtime/on-shutdown.md
      - Players:
        - reference/lifecycles/players/index.md
        - onPlayerAdded: reference/lifecycles/players/on-player-added.md
        - onPlayerRemoved: reference/lifecycles/players/on-player-removed.md
extra_css:
  - assets/theme/404.css
  - assets/theme/code.css
  - assets/theme/home.css
  - assets/theme/ompdoc.css
  - assets/theme/page.css
  - assets/theme/reference.css

extra:
  version:
    provider: mike

plugins:
  - search
  - mike:
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js

markdown_extensions:
  - toc:
      title: On this page
      permalink: true
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - docs/overrides/.icons
